services:
  db:
    image: postgres:16
    volumes:
      - ./backend/docker/db-init-script:/docker-entrypoint-initdb.d:cached
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    
  web:
    image: viewsonic_image
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    ports:
      - 8000:8000
    command: bash ./backend/docker/run_web.sh
    depends_on:
      - db
      - rabbitmq

  worker:
    image: viewsonic_image
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    command: bash ./backend/docker/run_worker.sh
    depends_on:
      - db
      - rabbitmq
  
  rabbitmq:
    hostname: management-alpine
    image: rabbitmq:4.0.3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_ERLANG_COOKIE=viewsonic
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - 15672:15672
  
  flower:
    image: viewsonic_image
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile
    ports:
      - 5555:5555
    command: bash ./backend/docker/run_flower.sh
    depends_on:
      - db
      - rabbitmq

volumes:
  db_data: {}