services:
  db:
    image: postgres:16
    volumes:
      - ./backend/docker/db-init-script:/docker-entrypoint-initdb.d:cached
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    
  web:
    image: viewsonic_web
    build:
      context: ./backend/
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    command: bash ./docker/run_web.sh
    depends_on:
      - db
      - rabbitmq
  
  rabbitmq:
    hostname: management-alpine
    image: rabbitmq:4.0.3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_ERLANG_COOKIE=viewsonic
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - 15672:15672
      # - 15692:15692

volumes:
  db_data: {}