from config.utils import get_config

CONFIG = get_config()
DATABASES = CONFIG["databases"]
DATABASE_URL = f"postgresql://{DATABASES["USER"]}:{DATABASES["PASSWORD"]}@{DATABASES["HOST"]}:{DATABASES["PORT"]}/{DATABASES["NAME"]}"
ASYNC_DATABASE_URL = f"postgresql+asyncpg://{DATABASES["USER"]}:{DATABASES["PASSWORD"]}@{DATABASES["HOST"]}:{DATABASES["PORT"]}/{DATABASES["NAME"]}"
ASYNC_TEST_DATABASE_URL = f"postgresql+asyncpg://{DATABASES["USER"]}:{DATABASES["PASSWORD"]}@{DATABASES["HOST"]}:{DATABASES["PORT"]}/{DATABASES["NAME"]}_test"

CACHE_LOCATION = CONFIG["cache"]["CACHE_LOCATION"]
